"use client"

import { createContext, useContext, useEffect, useState, ReactNode } from "react"
import { db } from "@/lib/firebase"
import { doc, onSnapshot } from "firebase/firestore"

export interface CongregationConfig {
    name: string
    shortName: string
    location: string
    logoUrl: string
    description: string
    themeColor: string
    driveFolderId: string
    features: {
        monitor: boolean
        ai: boolean
        audio: boolean
        annotations: boolean
        collaboration: boolean
    }
    printFooter: string
    defaultMusicians?: Array<{
        uid: string
        name: string
        instrument?: string
    }>
}

const DEFAULT_CONFIG: CongregationConfig = {
    name: "Central Reform Congregation",
    shortName: "CRC Music",
    location: "St. Louis, MO",
    logoUrl: "/logo.jpg",
    description: "Digital Sheet Music Library for CRC Musicians",
    themeColor: "#7c3aed",
    driveFolderId: "",
    features: {
        monitor: true,
        ai: true,
        audio: true,
        annotations: true,
        collaboration: true,
    },
    printFooter: "Generated by CRC Music Books",
}

const CACHE_KEY = 'crc_congregation'
const CACHE_TTL = 3600000 // 1 hour

function getCachedConfig(): CongregationConfig | null {
    if (typeof window === 'undefined') return null
    try {
        const raw = localStorage.getItem(CACHE_KEY)
        if (!raw) return null
        const parsed = JSON.parse(raw)
        if (Date.now() - (parsed._ts || 0) < CACHE_TTL) return parsed.data
    } catch { /* private browsing or corrupt */ }
    return null
}

function setCachedConfig(config: CongregationConfig) {
    try {
        localStorage.setItem(CACHE_KEY, JSON.stringify({ data: config, _ts: Date.now() }))
    } catch { /* quota exceeded */ }
}

const CongregationContext = createContext<CongregationConfig>(DEFAULT_CONFIG)

export function CongregationProvider({ children }: { children: ReactNode }) {
    // Initialize from localStorage cache for instant render (no Firestore round-trip)
    const [config, setConfig] = useState<CongregationConfig>(() => {
        return getCachedConfig() || DEFAULT_CONFIG
    })

    // Update from Firestore in the background — writes back to cache on change
    useEffect(() => {
        const ref = doc(db, "config", "congregation")
        const unsub = onSnapshot(
            ref,
            (snap) => {
                if (snap.exists()) {
                    const updated = { ...DEFAULT_CONFIG, ...snap.data() as Partial<CongregationConfig> }
                    setConfig(updated)
                    setCachedConfig(updated)
                }
            },
            () => {
                // Firestore error (offline, permissions) — cached/default already in use
            }
        )
        return unsub
    }, [])

    return (
        <CongregationContext.Provider value={config}>
            {children}
        </CongregationContext.Provider>
    )
}

export const useCongregation = () => useContext(CongregationContext)
