import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'
import { db } from "@/lib/firebase"
import { doc, onSnapshot } from "firebase/firestore"
import { logger } from "@/lib/logger"
import type { RabbiProfile } from "@/types/models"
import { DEFAULT_SHORT_NAME } from "@/lib/constants"

export interface CongregationConfig {
    name: string
    shortName: string
    location: string
    logoUrl: string
    description: string
    themeColor: string
    driveFolderId: string
    features: {
        monitor: boolean
        ai: boolean
        audio: boolean
        collaboration: boolean
    }
    printFooter: string
    defaultMusicians?: Array<{
        uid: string
        name: string
        instrument?: string
    }>
    scheduling?: {
        rabbiProfiles?: RabbiProfile[]
        defaultReminderHours?: number     // Hours before service to send reminder (default: 48)
        allowSelfScheduling?: boolean     // Can musicians volunteer for open slots?
    }
}

const DEFAULT_CONFIG: CongregationConfig = {
    name: "Central Reform Congregation",
    shortName: DEFAULT_SHORT_NAME,
    location: "St. Louis, MO",
    logoUrl: "/logo.jpg",
    description: "Digital Sheet Music Library for CRC Musicians",
    themeColor: "#7c3aed",
    driveFolderId: "",
    features: {
        monitor: true,
        ai: true,
        audio: true,
        collaboration: true,
    },
    printFooter: "Generated by CRC Music Books • a project of Rabbi Daniel Bogard",
}

interface CongregationStore {
    config: CongregationConfig
    isInitialized: boolean
    init: () => () => void // Returns an unsubscribe function
}

export const useCongregationStore = create<CongregationStore>()(
    persist(
        (set, get) => ({
            config: DEFAULT_CONFIG,
            isInitialized: false,
            init: () => {
                if (get().isInitialized) return () => { }
                if (typeof window === 'undefined') return () => { }

                const ref = doc(db, "config", "congregation")
                const unsub = onSnapshot(
                    ref,
                    (snap) => {
                        if (snap.exists()) {
                            const updated = { ...DEFAULT_CONFIG, ...snap.data() as Partial<CongregationConfig> }
                            set({ config: updated, isInitialized: true })
                        }
                    },
                    (err) => {
                        logger.error("[Congregation] Failed to sync config:", err)
                    }
                )

                set({ isInitialized: true })
                return () => {
                    unsub()
                    set({ isInitialized: false })
                }
            }
        }),
        {
            name: 'crc_congregation',
            storage: createJSONStorage(() => localStorage),
        }
    )
)

/**
 * Hook backwards-compatibility for components assuming they directly get the config object
 */
export const useCongregation = () => useCongregationStore(state => state.config)
