"use client"

import { createContext, useContext, useEffect, useState, ReactNode } from "react"
import { db } from "@/lib/firebase"
import { doc, onSnapshot } from "firebase/firestore"

export interface CongregationConfig {
    name: string
    shortName: string
    location: string
    logoUrl: string
    description: string
    themeColor: string
    driveFolderId: string
    features: {
        monitor: boolean
        ai: boolean
        audio: boolean
        annotations: boolean
        collaboration: boolean
    }
    printFooter: string
    defaultMusicians?: Array<{
        uid: string
        name: string
        instrument?: string
    }>
}

const DEFAULT_CONFIG: CongregationConfig = {
    name: "Central Reform Congregation",
    shortName: "CRC Music",
    location: "St. Louis, MO",
    logoUrl: "/logo.jpg",
    description: "Digital Sheet Music Library for CRC Musicians",
    themeColor: "#7c3aed",
    driveFolderId: "",
    features: {
        monitor: true,
        ai: true,
        audio: true,
        annotations: true,
        collaboration: true,
    },
    printFooter: "Generated by CRC Music Books",
}

const CongregationContext = createContext<CongregationConfig>(DEFAULT_CONFIG)

export function CongregationProvider({ children }: { children: ReactNode }) {
    const [config, setConfig] = useState<CongregationConfig>(DEFAULT_CONFIG)

    useEffect(() => {
        const ref = doc(db, "config", "congregation")
        const unsub = onSnapshot(
            ref,
            (snap) => {
                if (snap.exists()) {
                    setConfig({ ...DEFAULT_CONFIG, ...snap.data() as Partial<CongregationConfig> })
                }
            },
            () => {
                // Firestore error (offline, permissions) — use defaults silently
            }
        )
        return unsub
    }, [])

    return (
        <CongregationContext.Provider value={config}>
            {children}
        </CongregationContext.Provider>
    )
}

export const useCongregation = () => useContext(CongregationContext)
