import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'
import { auth, subscribeWithDb } from "@/lib/firebase"
// Phase 1.6 Option C-1 (cascading lazy) — `doc` and `onSnapshot` are imported
// DYNAMICALLY inside attachListener() below so /login's static-import graph
// doesn't pull the firestore SDK chunk through this module. congregation-store
// is loaded by every route via <ClientProviders> in root layout.tsx; keeping
// firestore off the module-top graph keeps `d94474cc-*.js` + cousin out of
// /login's preload manifest. See
// `.paul/research/bundle-diet-firestore-lazy-import/FINDINGS.md` §Phase-1.6.
import { onAuthStateChanged } from "firebase/auth"
import { logger } from "@/lib/logger"
import type { RabbiProfile } from "@/types/models"
import { DEFAULT_SHORT_NAME } from "@/lib/constants"

export interface CongregationConfig {
    name: string
    shortName: string
    location: string
    logoUrl: string
    description: string
    themeColor: string
    driveFolderId: string
    features: {
        monitor: boolean
        ai: boolean
        audio: boolean
        collaboration: boolean
    }
    printFooter: string
    defaultMusicians?: Array<{
        uid: string
        name: string
        instrument?: string
    }>
    scheduling?: {
        rabbiProfiles?: RabbiProfile[]
        defaultReminderHours?: number     // Hours before service to send reminder (default: 48)
        allowSelfScheduling?: boolean     // Can musicians volunteer for open slots?
    }
}

const DEFAULT_CONFIG: CongregationConfig = {
    name: "Central Reform Congregation",
    shortName: DEFAULT_SHORT_NAME,
    location: "St. Louis, MO",
    logoUrl: "/logo.jpg",
    description: "Digital Sheet Music Library for CRC Musicians",
    themeColor: "#7c3aed",
    driveFolderId: "",
    features: {
        monitor: true,
        ai: true,
        audio: true,
        collaboration: true,
    },
    printFooter: "Generated by CRC Music Books • a project of Rabbi Daniel Bogard",
}

interface CongregationStore {
    config: CongregationConfig
    isInitialized: boolean
    init: () => () => void // Returns an unsubscribe function
}

export const useCongregationStore = create<CongregationStore>()(
    persist(
        (set, get) => ({
            config: DEFAULT_CONFIG,
            isInitialized: false,
            init: () => {
                if (get().isInitialized) return () => { }
                if (typeof window === 'undefined') return () => { }

                // UNAUTH-002: firestore.rules require auth to read
                // `config/congregation`. Attaching the doc listener while
                // unauthenticated emits a permission-denied error on every
                // page load (console spam on /perform, /login, etc.).
                // Gate the listener on `auth.currentUser`; unauth surfaces
                // continue to use the persisted DEFAULT_CONFIG fallback.
                let firestoreUnsub: (() => void) | null = null
                // Phase 1.6 race-guard: attachListener became async (dynamic
                // `import("firebase/firestore")` adds a microtask boundary).
                // If the user signs out while a prior attach's import is in
                // flight, detachListener bumps the generation so the stale
                // attach's post-await assignment is skipped — otherwise we'd
                // leak a subscription tied to a signed-out session.
                let attachGen = 0

                const attachListener = async () => {
                    if (firestoreUnsub) return
                    const myGen = ++attachGen
                    const { doc, onSnapshot } = await import("firebase/firestore")
                    if (myGen !== attachGen || firestoreUnsub) return // detach fired or already attached
                    firestoreUnsub = subscribeWithDb((db) => onSnapshot(
                        doc(db, "config", "congregation"),
                        (snap) => {
                            if (snap.exists()) {
                                const updated = { ...DEFAULT_CONFIG, ...snap.data() as Partial<CongregationConfig> }
                                set({ config: updated, isInitialized: true })
                            }
                        },
                        (err) => {
                            logger.error("[Congregation] Failed to sync config:", err)
                        }
                    ))
                }

                const detachListener = () => {
                    attachGen++ // invalidate any in-flight attach awaiting the firestore module
                    if (firestoreUnsub) {
                        firestoreUnsub()
                        firestoreUnsub = null
                    }
                }

                const authUnsub = onAuthStateChanged(auth, (user) => {
                    if (user) void attachListener()
                    else detachListener()
                })

                set({ isInitialized: true })
                return () => {
                    authUnsub()
                    detachListener()
                    set({ isInitialized: false })
                }
            }
        }),
        {
            name: 'crc_congregation',
            storage: createJSONStorage(() => localStorage),
        }
    )
)

/**
 * Hook backwards-compatibility for components assuming they directly get the config object
 */
export const useCongregation = () => useCongregationStore(state => state.config)
